### ISSUE TITLE
联通Cookies如何获取

### ISSUE THREAD

**Issue by coffilk** [pujie1216/RushCoupon#7]
运行GetCookiespy3输入手机号并未收到任何登录验证码

**Comment by pujie1216** [comment]
可能是短信延迟了,只要号码是正确的且程序没有出错就肯定能收到短信

**Comment by coffilk** [comment]
确实是出错了，用idle运行后

> 功能选择:
> 
> 1 获取联通Cookies
> 
> 2 获取京东Cookies
> 
> 更多整合等待发现,欢迎回复提供
> 
> 请输入对应数字然后按确定:1
> 
> 请输入你的手机号:186xxxxxx
> 
> 是否需要发送验证码,上次获取了5分钟内未使用成功的可以继续用哦
> 是 直接按确定继续,否 输入 n 后按确定:
> 
> 可能程序出错了,正在重新运行程序
> 
> 请输入你的手机号:
没有其他提示

**Comment by pujie1216** [comment]
代码多人测试过，没有出现错误，随便更换一个11位号码试试

**Comment by pujie1216** [comment]
Over time
