### ISSUE TITLE
怎么突然就被永封了

### ISSUE THREAD

**Issue by death9394** [pujie1216/RushCoupon#8]

**Comment by Igonre** [comment]
大佬咋个情况？真心感谢大佬...跟小客搞一下

**Comment by pujie1216** [comment]
估计要支持我的人去联名跟小客说才行了，我一个人干不过

**Comment by Igonre** [comment]
> 估计要支持我的人去联名跟小客说才行了，我一个人干不过

大佬组个组织吧 等你哦

**Comment by mzyswy** [comment]
又是收费软件狗搞事？我去发帖去，支持大神的都去跟帖啊，还有大神啊，这个星期的代码有问题，虽然加入了询问是否需要捡漏的选项，但是又变成只能下单一个，支付完才能再次下单了

**Comment by Igonre** [comment]
> 又是收费软件狗搞事？我去发帖去，支持大神的都去跟帖啊，还有大神啊，这个星期的代码有问题，虽然加入了询问是否需要捡漏的选项，但是又变成只能下单一个，支付完才能再次下单

http://www.zuanke8.com/thread-7709366-1-1.html 看到啦 去给你加果

**Comment by lhd244547010** [comment]
> > 又是收费软件狗搞事？我去发帖去，支持大神的都去跟帖啊，还有大神啊，这个星期的代码有问题，虽然加入了询问是否需要捡漏的选项，但是又变成只能下单一个，支付完能力再次下单
> 
> http://www.zuanke8.com/thread-7709366-1-1.html看到啦去给你加果
已荚果

**Comment by magicjfy** [comment]
大佬还有5000多果呢 是直接封了还是重生了好像可以跟小客沟通把果果转出去的

**Comment by magicjfy** [comment]
可以搞个赞助二维码意思下。
另外求教下就是上午十点的提前挂上到点会自动抢，下午16点的过了时间还是一直显示等待抢购，不知道是哪里的问题，求解惑

**Comment by mzyswy** [comment]
搞明白了，代码没问题，有订单没支付闪退是假的，是我搞混了，联通好像改规则了，所有时间段每个商品只能抢一次，每个时间段貌似只能抢2个商品？抢多了就提示不要重复下单

**Comment by pujie1216** [comment]
> 搞明白了，代码没问题，有订单没支付闪退是假的，是我搞混了，联通好像改规则了，所有时间段每个商品只能抢一次，每个时间段貌似只能抢2个商品？抢多了就提示不要重复下单

本来联通就是只能同时卡一个未支付单的,大改规则那天估计是没设置好而已

**Comment by pujie1216** [comment]
> 可以搞个赞助二维码意思下。
> 另外求教下就是上午十点的提前挂上到点会自动抢，下午16点的过了时间还是一直显示等待抢购，不知道是哪里的问题，求解惑

py版还是exe版,我使用都正常,定时到了都会自动运行

**Comment by magicjfy** [comment]
> > 可以搞个赞助二维码意思下。
> > 另外求教下就是上午十点的提前挂上到点会自动抢，下午16点的过了时间还是一直显示等待抢购，不知道是哪里的问题，求解惑
> 
> py版还是exe版,我使用都正常,定时到了都会自动运行

py版本 那可能是下午的抢不到吧 我以为显示的16的点开始不行 哈哈 今天有人说手动就会提示火爆了

**Comment by mzyswy** [comment]
大神，py的时间是不是不大对，我这北京时间20点了，它那还是联通时间19点59分55秒，是联通的问题还是我的问题

**Comment by pujie1216** [comment]
> 大神，py的时间是不是不大对，我这北京时间20点了，它那还是联通时间19点59分55秒，是联通的问题还是我的问题

是不是你改过时间刷新间隔了?如果获取很频繁,时间接口会禁止访问一段时间的

**Comment by Dilute0** [comment]
大神，有群吗？

**Comment by pujie1216** [comment]
Over time
